<a href="https://colab.research.google.com/github/prashantmane091318/NLP/blob/main/NLP_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from trax import layers as tl

ModuleNotFoundError: ignored

In [ ]:
import trax

ModuleNotFoundError: ignored

In [ ]:
from utils import Layer, load_tweets, process_tweet

ModuleNotFoundError: ignored

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
sentence=["i love a dog","i really like a dog!","i loves cat","cat is not a pet animal"]

In [ ]:
t=Tokenizer(num_words=100,oov_token="<oov>")

In [ ]:
voc_size=10000

In [ ]:
t.fit_on_texts(sentence)

In [ ]:
word_index=t.word_index

In [ ]:
word_index

{'<oov>': 1,
 'a': 3,
 'animal': 13,
 'cat': 5,
 'dog': 4,
 'i': 2,
 'is': 10,
 'like': 8,
 'love': 6,
 'loves': 9,
 'not': 11,
 'pet': 12,
 'really': 7}

In [ ]:
sequence=t.texts_to_sequences(sentence)

In [ ]:
sequence

[[2, 6, 3, 4], [2, 7, 8, 3, 4], [2, 9, 5], [5, 10, 11, 3, 12, 13]]

In [ ]:
test=["i love you tpp"]

In [ ]:
seq=t.texts_to_sequences(test)

In [ ]:
seq

[[2, 6, 1, 1]]

In [ ]:
t.word_index

{'a': 2,
 'animal': 10,
 'cat': 4,
 'dog': 3,
 'i': 1,
 'is': 7,
 'like': 6,
 'love': 5,
 'loves': 12,
 'not': 8,
 'pet': 9,
 'really': 11}

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
padd=pad_sequences()

In [ ]:
padd

array([[ 0,  0,  2,  6,  3,  4],
       [ 0,  2,  7,  8,  3,  4],
       [ 0,  0,  0,  2,  9,  5],
       [ 5, 10, 11,  3, 12, 13]], dtype=int32)

In [ ]:
paddd=pad_sequences(sequence,padding="post",maxlen=5,truncating="post")

In [ ]:
paddd

array([[ 2,  6,  3,  4,  0],
       [ 2,  7,  8,  3,  4],
       [ 2,  9,  5,  0,  0],
       [ 5, 10, 11,  3, 12]], dtype=int32)

In [ ]:
import pandas as pd

In [ ]:
import json

In [ ]:
data=pd.read_json("/content/Sarcasm_Headlines_Dataset_v2.json",lines=True)

In [ ]:
data.head()

is_sarcastic  ...                                       article_link
0             1  ...  https://www.theonion.com/thirtysomething-scien...
1             0  ...  https://www.huffingtonpost.com/entry/donna-edw...
2             0  ...  https://www.huffingtonpost.com/entry/eat-your-...
3             1  ...  https://local.theonion.com/inclement-weather-p...
4             1  ...  https://www.theonion.com/mother-comes-pretty-c...

[5 rows x 3 columns]

In [ ]:
sentence=data["headline"]

In [ ]:
sentence[77
         ]

"defiant sanders camp: it ain't over"

In [ ]:
t1=Tokenizer(num_words=20000,oov_token="<oov>")

In [ ]:
t1.fit_on_texts(sentence)

In [ ]:
word_index=t1.word_index

In [ ]:
len(word_index)

30885

In [ ]:
word_index

{'<oov>': 1,
 'to': 2,
 'of': 3,
 'the': 4,
 'in': 5,
 'for': 6,
 'a': 7,
 'on': 8,
 'and': 9,
 'with': 10,
 'is': 11,
 'new': 12,
 'trump': 13,
 'man': 14,
 'at': 15,
 'from': 16,
 'about': 17,
 'by': 18,
 'after': 19,
 'you': 20,
 'this': 21,
 'out': 22,
 'up': 23,
 'be': 24,
 'as': 25,
 'that': 26,
 'it': 27,
 'how': 28,
 'not': 29,
 'he': 30,
 'his': 31,
 'are': 32,
 'your': 33,
 'just': 34,
 'what': 35,
 'all': 36,
 'who': 37,
 'has': 38,
 'will': 39,
 'report': 40,
 'into': 41,
 'more': 42,
 'one': 43,
 'have': 44,
 'year': 45,
 'over': 46,
 'why': 47,
 'day': 48,
 'u': 49,
 'area': 50,
 'woman': 51,
 'can': 52,
 's': 53,
 'says': 54,
 'donald': 55,
 'time': 56,
 'first': 57,
 'like': 58,
 'no': 59,
 'her': 60,
 'get': 61,
 'off': 62,
 'old': 63,
 "trump's": 64,
 'life': 65,
 'now': 66,
 'people': 67,
 "'": 68,
 'an': 69,
 'house': 70,
 'still': 71,
 'obama': 72,
 'white': 73,
 'back': 74,
 'make': 75,
 'was': 76,
 'than': 77,
 'women': 78,
 'if': 79,
 'down': 80,
 'when': 81,
 '

In [ ]:
seq=t1.texts_to_sequences(sentence)

In [ ]:
seq

[[1, 355, 3167, 7474, 2644, 3, 661, 1119],
 [7475, 1775, 758, 3168, 47, 239, 11, 1844, 1048, 8, 1528, 2154, 1845],
 [863, 33, 1, 262, 1, 647, 1484],
 [1, 1594, 6418, 5665, 16, 143, 2, 152],
 [472, 495, 322, 922, 2, 572, 550, 1, 6419],
 [83, 73, 1],
 [84, 280, 2, 4182, 33, 2515, 10, 573, 1356],
 [1846, 1, 777, 5063, 3169, 1120, 25, 227, 25, 1433, 3, 1434, 3359, 4183],
 [2961, 292, 143, 139, 1709, 2, 425, 5, 1, 1595, 356, 1357],
 [2792, 3, 160, 115, 21, 7476],
 [21, 2645, 11, 3360, 7, 426, 5, 3580, 9, 69, 1006, 43, 15, 26],
 [7477, 1, 648, 60, 536, 201, 11, 1358, 626, 1],
 [35, 2, 115, 1, 1710, 1, 6, 1049],
 [574, 1596, 953, 149, 85, 76, 2, 1776, 6, 9021, 1, 7478, 3, 1149, 3, 1],
 [1529, 4184, 12, 6420, 26, 1530, 1, 8, 9022],
 [1318, 379, 7479, 9023, 5064, 80, 16, 13, 1711, 7480, 2155],
 [50, 433, 1150, 5666, 9, 2156, 2793, 3, 1, 3361],
 [50, 14, 323, 100, 3, 31, 2261, 18, 1],
 [537, 59, 411, 10, 3362, 343],
 [3363, 3581, 2962, 98, 58, 2, 2516, 20, 2, 416, 33, 484, 259],
 [1319, 1712, 39

In [ ]:
pad=pad_sequences(seq)

In [ ]:
pad.shape

(28619, 152)

In [ ]:
for p in sentence:
  if len(p.split(" "))>30:
    print(p)

hot wheels ranked number one toy for rolling down ramp, knocking over dominoes that send marble down a funnel, dropping onto teeter-totter that yanks on string, causing pulley system to raise wooden block, propelling series of twine rollers that unwind spring, launching tennis ball across room, inching tire down slope until it hits power switch, activating table fan that blows toy ship with nail attached to it across kiddie pool, popping water balloon that fills cup, weighing down lever that forces basketball down track, nudging broomstick on axis to rotate, allowing golf ball to roll into sideways coffee mug, which tumbles down row of hardcover books until handle catches hook attached to lever that causes wooden mallet to slam down on serving spoon, catapulting small ball into cup attached by ribbon to lazy susan, which spins until it pushes d battery down incline plane, tipping over salt shaker to season omelet
'12 years a slave,' 'captain phillips,' 'american hustle,' 'wolf of wall 

In [ ]:
padd=pad_sequences(seq,padding="post",maxlen=40,truncating="post")

In [ ]:
padd.shape

(28619, 40)

In [ ]:
padd.shape

(28619, 40)

In [ ]:
padd[0]

array([   1,  355, 3167, 7474, 2644,    3,  661, 1119,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [ ]:
import tensorflow as tf
model=tf.keras.models.Sequential()

In [ ]:
model.add(tf.keras.layers.Embedding((20000,16,input_length=40,)))

In [ ]:
model.add(tf.keras.layers.Flatten())

In [ ]:
model.add(tf.keras.layers.Dense(24,activation="relu"))

In [ ]:
model.add(tf.keras.layers.Dense(1,activation="sigmoid"))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 40, 16)            320000    
_________________________________________________________________
flatten_1 (Flatten)          (None, 640)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 24)                15384     
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 25        
Total params: 335,409
Trainable params: 335,409
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [ ]:
padd.shape

(28619, 40)

In [ ]:
data.head()

is_sarcastic  ...                                       article_link
0             1  ...  https://www.theonion.com/thirtysomething-scien...
1             0  ...  https://www.huffingtonpost.com/entry/donna-edw...
2             0  ...  https://www.huffingtonpost.com/entry/eat-your-...
3             1  ...  https://local.theonion.com/inclement-weather-p...
4             1  ...  https://www.theonion.com/mother-comes-pretty-c...

[5 rows x 3 columns]

In [ ]:
label=data["is_sarcastic"]

In [ ]:
label

0        1
1        0
2        0
3        1
4        1
        ..
28614    1
28615    1
28616    0
28617    1
28618    1
Name: is_sarcastic, Length: 28619, dtype: int64

In [ ]:
label.shape

(28619,)

In [ ]:
model.fit(padd,label,batch_size=32,epochs=10)

Epoch 1/10
895/895 [==============================] - 4s 5ms/step - loss: 0.3891 - accuracy: 0.8151
Epoch 2/10
895/895 [==============================] - 4s 5ms/step - loss: 0.1943 - accuracy: 0.9231
Epoch 3/10
895/895 [==============================] - 4s 5ms/step - loss: 0.1040 - accuracy: 0.9634
Epoch 4/10
895/895 [==============================] - 4s 5ms/step - loss: 0.0430 - accuracy: 0.9872
Epoch 5/10
895/895 [==============================] - 4s 5ms/step - loss: 0.0148 - accuracy: 0.9966
Epoch 6/10
895/895 [==============================] - 4s 5ms/step - loss: 0.0052 - accuracy: 0.9991
Epoch 7/10
895/895 [==============================] - 4s 5ms/step - loss: 0.0021 - accuracy: 0.9998
Epoch 8/10
895/895 [==============================] - 4s 5ms/step - loss: 0.0013 - accuracy: 0.9997
Epoch 9/10
895/895 [==============================] - 4s 5ms/step - loss: 9.4389e-04 - accuracy: 0.9998
Epoch 10/10
895/895 [==============================] - 4s 5ms/step - loss: 0.0010 - accuracy: 0.

In [ ]:
lable_pr=model.predict(padd)


In [ ]:
lable_pr=np.round(lable_pr)

In [ ]:
lable_pr

array([[1.],
       [0.],
       [0.],
       ...,
       [0.],
       [1.],
       [1.]], dtype=float32)

In [ ]:
sum(lable_pr==np.array(label).reshape(-1,1))

array([28614])

In [ ]:
sentence1=["inclement weather prevents liar from getting to work","defiant sanders camp: it ain't over","Oh yes, you’ve been sooooo helpful. Thanks sooooo much for all your heeeelp","That's just what I needed today!","Really, Sherlock? No! You are clever.","hello how are you?","Nice perfume. How long did you marinate in it?","I love those mustard stains on your oversized hoodie. They really bring out the color in your eyes.","I work 40 hours a week for us to be this poor."]

In [ ]:
t1.fit_on_texts(sentence1)

In [ ]:
seqq=t1.texts_to_sequences(sentence1)

In [ ]:
seqq

[[1, 1594, 6418, 5665, 16, 143, 2, 152],
 [2970, 315, 1599, 27, 5677, 46],
 [3120, 1508, 1, 224, 1, 6068, 1209, 1, 227, 6, 36, 33, 1],
 [1066, 34, 35, 82, 1769, 541],
 [110, 1, 59, 20, 32, 4854],
 [1, 28, 32, 20],
 [1126, 1, 28, 225, 463, 20, 1, 5, 27],
 [82, 150, 589, 1, 1, 8, 33, 9222, 1, 87, 110, 713, 22, 4, 1151, 5, 33, 991],
 [82, 152, 702, 489, 7, 222, 6, 241, 2, 24, 21, 927]]

In [ ]:
paa=pad_sequences(seqq,padding="post",maxlen=40,truncating="post")

In [ ]:
paa

array([[3120, 1508,    1,  224,    1, 6068, 1209,    1,  227,    6,   36,
          33,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],
       [1066,   34,   35,   82, 1769,  541,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],
       [ 110,    1,   59,   20,   32, 4854,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],
       [   1,   28,   32,   20,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,  

In [ ]:
paa.shape

(9, 40)

In [ ]:
np.round(model.predict(paa))

array([[1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [ ]:
data["is_sarcastic"]

0        1
1        0
2        0
3        1
4        1
        ..
28614    1
28615    1
28616    0
28617    1
28618    1
Name: is_sarcastic, Length: 28619, dtype: int64

In [ ]:
sentence[3]

'inclement weather prevents liar from getting to work'