<a href="https://colab.research.google.com/github/prashantmane091318/NLP/blob/main/NLP_Word_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
data="in the one town of athy one jersey langing\n battered away till he didnt find\n akshay working as engineer\n akshay gone mad"

In [ ]:
corpous=data.lower().split("\n")

In [ ]:
corpous

['in the one town of athy one jersey langing',
 ' battered away till he didnt find',
 ' akshay working as engineer',
 ' akshay gone mad']

In [ ]:
t1=Tokenizer()

In [ ]:
t1

In [ ]:
t1.fit_on_texts(corpous)

In [ ]:
t1

In [ ]:
word_count=len(t1.word_index)+1

In [ ]:
seqq=t1.texts_to_sequences(corpous)

In [ ]:
seqq

[[3, 4, 2, 5, 6, 7, 2, 8, 9],
 [10, 11, 12, 13, 14, 15],
 [1, 16, 17, 18],
 [1, 19, 20]]

In [ ]:
input_sequneces=[]
for line in seqq:
  for i in range(1,len(line)):
    n_gram_tokens=line[:i+1]
    input_sequneces.append(n_gram_tokens)

In [ ]:
input_sequneces

[[2, 3],
 [2, 3, 4],
 [2, 3, 4, 5],
 [2, 3, 4, 5, 6],
 [2, 3, 4, 5, 6, 7],
 [2, 3, 4, 5, 6, 7, 8],
 [2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11],
 [10, 11, 12],
 [10, 11, 12, 13],
 [10, 11, 12, 13, 14],
 [10, 11, 12, 13, 14, 15],
 [1, 16],
 [1, 16, 17],
 [1, 16, 17, 18],
 [1, 19],
 [1, 19, 20]]

In [ ]:
maxlen=max(len(x) for x in input_sequneces)

In [ ]:
maxlen

8

In [ ]:
pad_input=pad_sequences(input_sequneces,padding="pre",maxlen=maxlen-1)

In [ ]:
pad_input

array([[ 0,  0,  0,  0,  0,  2,  3],
       [ 0,  0,  0,  0,  2,  3,  4],
       [ 0,  0,  0,  2,  3,  4,  5],
       [ 0,  0,  2,  3,  4,  5,  6],
       [ 0,  2,  3,  4,  5,  6,  7],
       [ 2,  3,  4,  5,  6,  7,  8],
       [ 3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0,  0, 10, 11],
       [ 0,  0,  0,  0, 10, 11, 12],
       [ 0,  0,  0, 10, 11, 12, 13],
       [ 0,  0, 10, 11, 12, 13, 14],
       [ 0, 10, 11, 12, 13, 14, 15],
       [ 0,  0,  0,  0,  0,  1, 16],
       [ 0,  0,  0,  0,  1, 16, 17],
       [ 0,  0,  0,  1, 16, 17, 18],
       [ 0,  0,  0,  0,  0,  1, 19],
       [ 0,  0,  0,  0,  1, 19, 20]], dtype=int32)

In [ ]:
xs,labels=pad_input[:,:-1],pad_input[:,-1]

In [ ]:
xs

array([[ 0,  0,  0,  0,  0,  2],
       [ 0,  0,  0,  0,  2,  3],
       [ 0,  0,  0,  2,  3,  4],
       [ 0,  0,  2,  3,  4,  5],
       [ 0,  2,  3,  4,  5,  6],
       [ 2,  3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7,  8],
       [ 0,  0,  0,  0,  0, 10],
       [ 0,  0,  0,  0, 10, 11],
       [ 0,  0,  0, 10, 11, 12],
       [ 0,  0, 10, 11, 12, 13],
       [ 0, 10, 11, 12, 13, 14],
       [ 0,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  1, 16],
       [ 0,  0,  0,  1, 16, 17],
       [ 0,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  1, 19]], dtype=int32)

In [ ]:
labels

array([ 3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
      dtype=int32)

In [ ]:
ys=tf.keras.utils.to_categorical(labels,num_classes=word_count)

In [ ]:
ys.shape

(17, 21)

In [ ]:
xs.shape

(17, 7)

In [ ]:
xs[5]

array([0, 2, 3, 4, 5, 6, 7], dtype=int32)

In [ ]:
ys[5]

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.], dtype=float32)

In [ ]:
model=tf.keras.models.Sequential()

In [ ]:
from tensorflow.keras.layers import LSTM,Dense,Embedding,Bidirectional

In [ ]:
model.add(Embedding(word_count,64,input_length=maxlen))

In [ ]:
model.add(Bidirectional(LSTM(64)))

In [ ]:
model.add(Dense(word_count,activation="softmax"))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 64)             1344      
_________________________________________________________________
bidirectional_1 (Bidirection (None, 128)               66048     
_________________________________________________________________
dense_1 (Dense)              (None, 21)                2709      
Total params: 70,101
Trainable params: 70,101
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [ ]:
model.fit(xs,ys,batch_size=32,epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 2ms/step - loss: 3.0446 - accuracy: 0.1176
Epoch 2/500
1/1 [==============================] - 0s 1ms/step - loss: 3.0387 - accuracy: 0.0588
Epoch 3/500
1/1 [==============================] - 0s 2ms/step - loss: 3.0327 - accuracy: 0.1765
Epoch 4/500
1/1 [==============================] - 0s 1ms/step - loss: 3.0267 - accuracy: 0.1765
Epoch 5/500
1/1 [==============================] - 0s 1ms/step - loss: 3.0206 - accuracy: 0.1765
Epoch 6/500
1/1 [==============================] - 0s 1ms/step - loss: 3.0143 - accuracy: 0.1765
Epoch 7/500
1/1 [==============================] - 0s 1ms/step - loss: 3.0078 - accuracy: 0.2941
Epoch 8/500
1/1 [==============================] - 0s 2ms/step - loss: 3.0009 - accuracy: 0.2353
Epoch 9/500
1/1 [==============================] - 0s 2ms/step - loss: 2.9936 - accuracy: 0.2353
Epoch 10/500
1/1 [==============================] - 0s 2ms/step - loss: 2.9859 - accuracy: 0.2353
Epoch 11/500
1/1 [===========

In [ ]:
ss=["in the town of athy one","in the town of athy one jersey","akshay working as","akshay is","mad"]

In [ ]:
ssq=t1.texts_to_sequences(ss)

In [ ]:
token_ssq1=pad_sequences(ssq,padding="pre",maxlen=maxlen-1)

In [ ]:
pr=model.predict_classes(token_ssq1)

In [ ]:
token_ssq1.shape

(5, 7)

In [ ]:
pr

array([ 7,  9, 18, 16, 20])

In [ ]:
t1.word_index

{'akshay': 1,
 'as': 17,
 'athy': 6,
 'away': 11,
 'battered': 10,
 'didnt': 14,
 'engineer': 18,
 'find': 15,
 'gone': 19,
 'he': 13,
 'in': 2,
 'jersey': 8,
 'langing': 9,
 'mad': 20,
 'of': 5,
 'one': 7,
 'the': 3,
 'till': 12,
 'town': 4,
 'working': 16}