<a href="https://colab.research.google.com/github/prashantmane091318/NLP/blob/main/NLP_Deep_Learning_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
data=tf.keras.datasets.imdb

In [ ]:
(xtrain,ytrain),(xtest,ytest)=data.load_data()

17465344/17464789 [==============================] - 0s 0us/step


<string>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/datasets/imdb.py:159: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/datasets/imdb.py:160: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 

In [ ]:
xtrain.shape

(25000,)

In [ ]:
xtest.shape

(25000,)

In [ ]:
ytrain.shape

(25000,)

In [ ]:
ytest.shape

(25000,)

In [ ]:
xtrain[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [ ]:
import tensorflow_datasets as tfds

In [ ]:
imdb,info=tfds.load("imdb_reviews",as_supervised=True,with_info=True)

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteV2BZGY/imdb_reviews-train.tfrecord


Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteV2BZGY/imdb_reviews-test.tfrecord


Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteV2BZGY/imdb_reviews-unsupervised.tfrecord


Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0. Subsequent calls will reuse this data.


In [ ]:
imdb

{'test': <PrefetchDataset shapes: ((), ()), types: (tf.string, tf.int64)>,
 'train': <PrefetchDataset shapes: ((), ()), types: (tf.string, tf.int64)>,
 'unsupervised': <PrefetchDataset shapes: ((), ()), types: (tf.string, tf.int64)>}

In [ ]:
train_data,test_data=imdb["train"],imdb["test"]

In [ ]:
training_sequences=[]
testing_sequences=[]
training_labels=[]
testing_labels=[]
for i,l in train_data:
  training_sequences.append(str(i.numpy()))
  training_labels.append(l.numpy())
for i,l in test_data:
  testing_sequences.append(str(i.numpy()))
  testing_labels.append(l.numpy())

In [ ]:
training_sequences[0]

'b"This was an absolutely terrible movie. Don\'t be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie\'s ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor\'s like Christopher Walken\'s good name. I could barely sit through it."'

In [ ]:
training_labels[0]

0

In [ ]:
info

tfds.core.DatasetInfo(
    name='imdb_reviews',
    version=1.0.0,
    description='Large Movie Review Dataset.
This is a dataset for binary sentiment classification containing substantially more data than previous benchmark datasets. We provide a set of 25,000 highly polar movie reviews for training, and 25,000 for testing. There is additional unlabeled data for use as well.',
    homepage='http://ai.stanford.edu/~amaas/data/sentiment/',
    features=FeaturesDict({
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=2),
        'text': Text(shape=(), dtype=tf.string),
    }),
    total_num_examples=100000,
    splits={
        'test': 25000,
        'train': 25000,
        'unsupervised': 50000,
    },
    supervised_keys=('text', 'label'),
    citation="""@InProceedings{maas-EtAl:2011:ACL-HLT2011,
      author    = {Maas, Andrew L.  and  Daly, Raymond E.  and  Pham, Peter T.  and  Huang, Dan  and  Ng, Andrew Y.  and  Potts, Christopher},
      title     = {Learning Word

In [ ]:
voc_size=10000
emb_size=16
maxlen=120


In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
t1=Tokenizer(voc_size,oov_token="<oov>")

In [ ]:
t1.fit_on_texts(training_sequences)

In [ ]:
word_index=t1.word_index

In [ ]:
len(word_index)

86539

In [ ]:
seq=t1.texts_to_sequences(training_sequences)

In [ ]:
len(seq[0])

118

In [ ]:
pp=training_sequences[0]

In [ ]:
pp1=pp.split(" ")

In [ ]:
len(pp1)

116

In [ ]:
pp1

['b"This',
 'was',
 'an',
 'absolutely',
 'terrible',
 'movie.',
 "Don't",
 'be',
 'lured',
 'in',
 'by',
 'Christopher',
 'Walken',
 'or',
 'Michael',
 'Ironside.',
 'Both',
 'are',
 'great',
 'actors,',
 'but',
 'this',
 'must',
 'simply',
 'be',
 'their',
 'worst',
 'role',
 'in',
 'history.',
 'Even',
 'their',
 'great',
 'acting',
 'could',
 'not',
 'redeem',
 'this',
 "movie's",
 'ridiculous',
 'storyline.',
 'This',
 'movie',
 'is',
 'an',
 'early',
 'nineties',
 'US',
 'propaganda',
 'piece.',
 'The',
 'most',
 'pathetic',
 'scenes',
 'were',
 'those',
 'when',
 'the',
 'Columbian',
 'rebels',
 'were',
 'making',
 'their',
 'cases',
 'for',
 'revolutions.',
 'Maria',
 'Conchita',
 'Alonso',
 'appeared',
 'phony,',
 'and',
 'her',
 'pseudo-love',
 'affair',
 'with',
 'Walken',
 'was',
 'nothing',
 'but',
 'a',
 'pathetic',
 'emotional',
 'plug',
 'in',
 'a',
 'movie',
 'that',
 'was',
 'devoid',
 'of',
 'any',
 'real',
 'meaning.',
 'I',
 'am',
 'disappointed',
 'that',
 'there'

In [ ]:
seq[0]

[59,
 12,
 14,
 35,
 439,
 400,
 18,
 174,
 29,
 1,
 9,
 33,
 1378,
 3401,
 42,
 496,
 1,
 197,
 25,
 88,
 156,
 19,
 12,
 211,
 340,
 29,
 70,
 248,
 213,
 9,
 486,
 62,
 70,
 88,
 116,
 99,
 24,
 5740,
 12,
 3317,
 657,
 777,
 12,
 18,
 7,
 35,
 406,
 8228,
 178,
 2477,
 426,
 2,
 92,
 1253,
 140,
 72,
 149,
 55,
 2,
 1,
 7525,
 72,
 229,
 70,
 2962,
 16,
 1,
 2880,
 1,
 1,
 1506,
 4998,
 3,
 40,
 3947,
 119,
 1608,
 17,
 3401,
 14,
 163,
 19,
 4,
 1253,
 927,
 7986,
 9,
 4,
 18,
 13,
 14,
 4200,
 5,
 102,
 148,
 1237,
 11,
 240,
 692,
 13,
 44,
 25,
 101,
 39,
 12,
 7232,
 1,
 39,
 1378,
 1,
 52,
 409,
 11,
 99,
 1214,
 874,
 145,
 10]

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
padd=pad_sequences(seq,maxlen=maxlen,padding="post",truncating="post")

In [ ]:
padd

array([[  59,   12,   14, ...,   10,    0,    0],
       [ 256,   28,   78, ...,    0,    0,    0],
       [   1, 6175,    2, ...,  564,    5,  746],
       ...,
       [7629,   37,   11, ...,  168,    6,   29],
       [2677,   11,  216, ...,  249,   96,   45],
       [3875,    5,   31, ...,   17,    1,   11]], dtype=int32)

In [ ]:
import numpy as np

In [ ]:
training_labels_final=np.array(training_labels)

In [ ]:
testing_labels_final=np.array(testing_labels)

In [ ]:
training_labels_final

array([0, 0, 0, ..., 0, 0, 1])

In [ ]:
testing_labels_final

array([1, 1, 0, ..., 0, 1, 1])

In [ ]:
model=tf.keras.models.Sequential()

In [ ]:
from tensorflow.keras.layers import Embedding,Flatten,Dense

In [ ]:
model.add(Embedding(voc_size,emb_size,input_length=maxlen))

In [ ]:

model.add(Flatten())

In [ ]:
model.add(Dense(50,activation="relu"))

In [ ]:
model.add(Dense(1,activation="sigmoid"))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 120, 16)           160000    
_________________________________________________________________
flatten (Flatten)            (None, 1920)              0         
_________________________________________________________________
dense (Dense)                (None, 50)                96050     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 51        
Total params: 256,101
Trainable params: 256,101
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [ ]:
model.fit(padd,training_labels_final,batch_size=32,epochs=10)

Epoch 1/10
782/782 [==============================] - 3s 4ms/step - loss: 0.4624 - accuracy: 0.7636
Epoch 2/10
782/782 [==============================] - 3s 4ms/step - loss: 0.2052 - accuracy: 0.9216
Epoch 3/10
782/782 [==============================] - 3s 4ms/step - loss: 0.0457 - accuracy: 0.9875
Epoch 4/10
782/782 [==============================] - 3s 4ms/step - loss: 0.0059 - accuracy: 0.9993
Epoch 5/10
782/782 [==============================] - 3s 4ms/step - loss: 9.5231e-04 - accuracy: 1.0000
Epoch 6/10
782/782 [==============================] - 3s 4ms/step - loss: 4.0582e-04 - accuracy: 1.0000
Epoch 7/10
782/782 [==============================] - 3s 4ms/step - loss: 2.0779e-04 - accuracy: 1.0000
Epoch 8/10
782/782 [==============================] - 3s 4ms/step - loss: 1.1856e-04 - accuracy: 1.0000
Epoch 9/10
782/782 [==============================] - 3s 4ms/step - loss: 7.3618e-05 - accuracy: 1.0000
Epoch 10/10
782/782 [==============================] - 3s 4ms/step - loss: 4.489

ValueError: ignored

In [ ]:
seq_test=t1.texts_to_sequences(testing_sequences)

In [ ]:
padd_test=pad_sequences(seq_test,maxlen=maxlen,padding="post",truncating="post")

In [ ]:
model.evaluate(padd_test,testing_labels_final)

782/782 [==============================] - 2s 2ms/step - loss: 1.0894 - accuracy: 0.8030


[1.0893585681915283, 0.8030400276184082]

In [ ]:
sentence=["movie was good rating best movie scene best actors","movie was bad rating bad movie scene bad actors"]

In [ ]:
seqq=t1.texts_to_sequences(sentence)

In [ ]:
pad_seqq=pad_sequences(seqq,maxlen=maxlen,padding="post",truncating="post")

In [ ]:
pad_seqq

array([[ 18,  14,  52, 683, 120,  18, 137, 120, 156,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [ 18,  14,  80, 683,  80,  18, 137,  80, 156,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,

In [ ]:
model.predict(pad_seqq)

array([[9.0010184e-01],
       [2.4024200e-06]], dtype=float32)

In [ ]:
t2=Tokenizer(3)

In [ ]:
sentence11=["my name is far faraway asdasd", "my name is","my your name is "]

In [ ]:
t2.fit_on_texts(sentence11)

In [ ]:
seqs=t2.texts_to_sequences(sentence11)

In [ ]:
seqs

[[1, 2], [1, 2], [1, 2]]

In [ ]:
t2.word_index

{'asdasd': 6, 'far': 4, 'faraway': 5, 'is': 3, 'my': 1, 'name': 2, 'your': 7}

In [ ]:
padd

array([[  59,   12,   14, ...,   10,    0,    0],
       [ 256,   28,   78, ...,    0,    0,    0],
       [   1, 6175,    2, ...,  564,    5,  746],
       ...,
       [7629,   37,   11, ...,  168,    6,   29],
       [2677,   11,  216, ...,  249,   96,   45],
       [3875,    5,   31, ...,   17,    1,   11]], dtype=int32)

In [ ]:
padd.shape

(25000, 120)

In [ ]:
model1=tf.keras.models.Sequential()

In [ ]:
from tensorflow.keras.layers import LSTM,Bidirectional

In [ ]:
model1.add(Embedding(voc_size,16,input_length=maxlen))

In [ ]:
model1.add(Bidirectional(LSTM(50)))

In [ ]:
model1.add(Dense(50,activation="relu"))

In [ ]:
model1.add(Dense(1,activation="sigmoid"))

In [ ]:
model1.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 120, 16)           160000    
_________________________________________________________________
bidirectional (Bidirectional (None, 100)               26800     
_________________________________________________________________
dense_2 (Dense)              (None, 50)                5050      
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 51        
Total params: 191,901
Trainable params: 191,901
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model1.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [ ]:
model1.fit(padd,training_labels_final,batch_size=32,epochs=10)

Epoch 1/10
782/782 [==============================] - 11s 14ms/step - loss: 0.4615 - accuracy: 0.7719
Epoch 2/10
782/782 [==============================] - 11s 14ms/step - loss: 0.2941 - accuracy: 0.8824
Epoch 3/10
782/782 [==============================] - 11s 14ms/step - loss: 0.2406 - accuracy: 0.9084
Epoch 4/10
782/782 [==============================] - 11s 14ms/step - loss: 0.1903 - accuracy: 0.9282
Epoch 5/10
782/782 [==============================] - 11s 14ms/step - loss: 0.1380 - accuracy: 0.9498
Epoch 6/10
782/782 [==============================] - 11s 14ms/step - loss: 0.0975 - accuracy: 0.9659
Epoch 7/10
782/782 [==============================] - 11s 14ms/step - loss: 0.0688 - accuracy: 0.9767
Epoch 8/10
782/782 [==============================] - 11s 14ms/step - loss: 0.0476 - accuracy: 0.9845
Epoch 9/10
782/782 [==============================] - 11s 14ms/step - loss: 0.0418 - accuracy: 0.9861
Epoch 10/10
782/782 [==============================] - 11s 14ms/step - loss: 0.038

In [ ]:
model1.evaluate(padd_test,testing_labels_final)

782/782 [==============================] - 4s 5ms/step - loss: 0.9515 - accuracy: 0.7791


[0.951484739780426, 0.7790799736976624]